<?php
/**
 * InlineResponse200DataFilePathsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Baokim CDN API Documentation
 *
 * Manage & serve Baokim static files
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@baokim.vn
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200DataFilePathsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200DataFilePaths
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200DataFilePathsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200DataFilePaths"
     */
    public function testInlineResponse200DataFilePaths()
    {
    }

    /**
     * Test attribute "file_name1"
     */
    public function testPropertyFileName1()
    {
    }

    /**
     * Test attribute "file_name2"
     */
    public function testPropertyFileName2()
    {
    }
}
